# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: "Paperless-GPT (DEV)"
version: "0.27.0"
slug: paperless-gpt-dev
stage: experimental
description: "AI-powered companion for Paperless-NGX to automatically categorize and extract metadata from your documents."
url: "https://github.com/connormxy/homeassistant-paperless-gpt#dev"
arch:
  - aarch64
  - amd64
init: false
hassio_role: default
privileged: []
homeassistant_api: false
options:
  PAPERLESS_BASE_URL: "http://paperless-ngx:8000"
  PAPERLESS_API_TOKEN: ""
  LLM_PROVIDER: "openai"
  LLM_MODEL: "gpt-4o"
  OPENAI_API_KEY: ""
  MANUAL_TAG: "paperless-gpt"
  AUTO_TAG: "paperless-gpt-auto"
  FAIL_TAG: "paperless-gpt-failed"
  CREATE_LOCAL_PDF: false
  CREATE_LOCAL_HOCR: false
  PDF_REPLACE: false
schema:
  PAPERLESS_BASE_URL: str
  PAPERLESS_API_TOKEN: password
  PAPERLESS_PUBLIC_URL: str?
  LLM_PROVIDER: list(openai|ollama|googleai|mistral|anthropic)
  LLM_MODEL: str
  OPENAI_API_KEY: password?
  MISTRAL_API_KEY: password?
  ANTHROPIC_API_KEY: password?
  GOOGLEAI_API_KEY: password?
  OPENAI_API_TYPE: str?
  TOKEN_LIMIT: int?
  OLLAMA_CONTEXT_LENGTH: int?
  OLLAMA_HEADERS: str?
  MANUAL_TAG: str
  AUTO_TAG: str
  FAIL_TAG: str
  AUTO_TAG_COMPLETE: str?
  OCR_LIMIT_PAGES: int?
  CREATE_LOCAL_PDF: bool
  CREATE_LOCAL_HOCR: bool
  PDF_REPLACE: bool
map:
  - share:rw
  - addon_config:rw
webui: "http://[HOST]:[PORT:8080]"
ports:
  8080/tcp: 18080
ports_description:
  8080/tcp: "Paperless-GPT Web Interface"
