name: "Paperless GPT"
version: "1.0.0"
slug: "paperless-gpt"
description: "A Home Assistant add-on for Paperless GPT."
arch:
  - amd64
  - armv7
  - aarch64
startup: "application"
boot: "auto"
ports:
  8080/tcp: 8080
ingress: true
ingress_port: 8080
map:
  - addon_config:rw
options:
  PAPERLESS_BASE_URL: "http://ca5234a0-paperless-ngx:80"
  PAPERLESS_API_TOKEN: ""
  LLM_PROVIDER: ""
  LLM_MODEL: ""
  OPENAI_API_KEY: ""
  OLLAMA_HOST: "http://76e18fb5-ollama:11434"
  PAPERLESS_INSECURE_SKIP_VERIFY: false
  CORRESPONDENT_BLACK_LIST: ""
  AZURE_DOCAI_ENDPOINT: ""
  AZURE_DOCAI_KEY: ""
  AZURE_DOCAI_MODEL_ID: ""
  AZURE_DOCAI_TIMEOUT_SECONDS: ""
  AZURE_DOCAI_OUTPUT_CONTENT_FORMAT: ""
  MANUAL_TAG: "paperless-gpt"
  AUTO_TAG: "paperless-gpt-auto"
  MANUAL_OCR_TAG: "paperless-gpt-ocr"
  AUTO_OCR_TAG: "paperless-gpt-ocr-auto"
  VISION_LLM_PROVIDER: ""
  VISION_LLM_MODEL: ""
  LOG_LEVEL: "info"
  LISTEN_INTERFACE: ":8080"
  AUTO_GENERATE_TITLE: "true"
  AUTO_GENERATE_TAGS: "true"
  AUTO_GENERATE_CORRESPONDENTS: "true"
  AUTO_GENERATE_CREATED_DATE: "true"
  OCR_LIMIT_PAGES: "5"
  TOKEN_LIMIT: "0"
  OCR_PROVIDER: "llm"
  GOOGLE_PROJECT_ID: ""
  GOOGLE_LOCATION: ""
  GOOGLE_PROCESSOR_ID: ""
  LLM_LANGUAGE: "English"
  PAPERLESS_PUBLIC_URL: ""
schema:
  PAPERLESS_BASE_URL: "url"
  PAPERLESS_API_TOKEN: "password"
  LLM_PROVIDER: "list(openai|ollama)"
  LLM_MODEL: "str"
  OPENAI_API_KEY: "password"
  OLLAMA_HOST: "url"
  PAPERLESS_INSECURE_SKIP_VERIFY: "bool"
  CORRESPONDENT_BLACK_LIST: "str"
  AZURE_DOCAI_ENDPOINT: "url?"
  AZURE_DOCAI_KEY: "password?"
  AZURE_DOCAI_MODEL_ID: "str?"
  AZURE_DOCAI_TIMEOUT_SECONDS: "int?"
  AZURE_DOCAI_OUTPUT_CONTENT_FORMAT: "str?"
  MANUAL_TAG: "str"
  AUTO_TAG: "str"
  MANUAL_OCR_TAG: "str"
  AUTO_OCR_TAG: "str"
  VISION_LLM_PROVIDER: "list(openai|ollama)?"
  VISION_LLM_MODEL: "str?"
  LOG_LEVEL: "list(debug|info|warn|error)"
  LISTEN_INTERFACE: "str"
  AUTO_GENERATE_TITLE: "bool"
  AUTO_GENERATE_TAGS: "bool"
  AUTO_GENERATE_CORRESPONDENTS: "bool"
  AUTO_GENERATE_CREATED_DATE: "bool"
  OCR_LIMIT_PAGES: "int"
  TOKEN_LIMIT: "int"
  OCR_PROVIDER: "list(llm|azure|google)?"
  GOOGLE_PROJECT_ID: "str?"
  GOOGLE_LOCATION: "str?"
  GOOGLE_PROCESSOR_ID: "str?"
  LLM_LANGUAGE: "str"
  PAPERLESS_PUBLIC_URL: "url?"
image: "ghcr.io/connormxy/homeassistant-paperless-gpt/{arch}-addon"
webui: "http://[HOST]:[PORT:8080]"
